spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey:
    secretkey:
