spring:
  main:
    allow-bean-definition-overriding: true

amazon:
  dynamodb:
    endpoint: https://us-east-2.console.aws.amazon.com/dynamodb/home?region=us-east-2
    accesskey: ${AWS_ACCESS_KEY_ID}
    secretkey: ${AWS_SECRET_KEY}
