package com.thezer0team.shredderapi.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

import javax.persistence.Entity

@DynamoDBTable(tableName = "applicationCalendarEvent")
class ApplicationCalendarEventEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String eventId

    @DynamoDBAttribute
    String nativeEventId
}
