package com.thezer0team.shredderapi.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "calendar_event")
class ApplicationCalendarEventEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String eventId

    @DynamoDBAttribute
    String nativeEventId

    @DynamoDBAttribute
    Set<ApplicationCalendarEntity> calendars
}
