package com.thezer0team.shredderapi.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "application_calendar")
class ApplicationCalendarEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String calendarId

    @DynamoDBAttribute
    UserEntity user

    @DynamoDBAttribute
    BigInteger applicationCalendarId

    @DynamoDBAttribute
    String name

    @DynamoDBAttribute
    Set<ApplicationCalendarEventEntity> events
}
