package com.thezer0team.shredderapi.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table
import java.time.Instant

@DynamoDBTable(tableName = "platform_event")
class PlatformEventEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String platformCalendarId

    @DynamoDBAttribute
    PlatformCalendarEntity platformCalendar

    @DynamoDBAttribute
    String name

    @DynamoDBAttribute
    String description

    @DynamoDBAttribute
    Instant startTime

    @DynamoDBAttribute
    Instant endTime

    @DynamoDBAttribute//TODO research location objects
    String location
}
