package com.thezer0team.shredderapi.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "platform_calendar")
class PlatformCalendarEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String platformCalendarId

    @DynamoDBAttribute
    String sourceType

    @DynamoDBAttribute
    BigInteger applicationCalendarId

    @DynamoDBAttribute
    String name

    @DynamoDBAttribute
    Set<PlatformEventEntity> events


}
