package com.thezer0team.shredderapi.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "user")
class UserEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String userId

    @DynamoDBAttribute
    String userName

    @DynamoDBAttribute
    String userEmail

    @DynamoDBAttribute
    ApplicationCalendarEntity applicationCalendar
}
